## CA2 ##
## IRELAND AGRICULTURE PRODUCTION COMPARED TO OTHER COUNTRIES

1. Step 1 : Exploratory Data Analysis
2. Step 2 : Statistics
3. Step 3 : ML Model around our data
4. Step 4 : Optimization with Python

In [1]:
#import of library for exploration of data
import pandas as pd
import numpy as np
import seaborn as sns
import math
import matplotlib.pyplot as plt

# We can suppress the warnings for a better reading
import warnings
warnings.filterwarnings('ignore')

# 1. Exploratory Data Analysis

In [2]:
#Source data generated from the link below
#https://www.fao.org/faostat/en/#data/QV

# Applied filter
# Country = Ireland, Year Only last 5 years including 2016,2017,2018,2019,2020 (2021,2022 data are not available yet)

#Read files from Eurostat - Agriculture Production Value
ag_production_value = "faostat/irl_fr_sp_usa.csv"
ag_prod_value_df = pd.read_csv(ag_production_value)

#Quick Overview of the data
ag_prod_value_df.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,QV,Value of Agricultural Production,250,France,152,Gross Production Value (constant 2014-2016 tho...,01371,"Almonds, in shell",2018,2018,1000 Int. $,5713,E,Estimated value
1,QV,Value of Agricultural Production,250,France,152,Gross Production Value (constant 2014-2016 tho...,01371,"Almonds, in shell",2019,2019,1000 Int. $,5713,E,Estimated value
2,QV,Value of Agricultural Production,250,France,152,Gross Production Value (constant 2014-2016 tho...,01371,"Almonds, in shell",2020,2020,1000 Int. $,5916,E,Estimated value
3,QV,Value of Agricultural Production,250,France,152,Gross Production Value (constant 2014-2016 tho...,01341,Apples,2018,2018,1000 Int. $,821448,E,Estimated value
4,QV,Value of Agricultural Production,250,France,152,Gross Production Value (constant 2014-2016 tho...,01341,Apples,2019,2019,1000 Int. $,827655,E,Estimated value

In [3]:
ag_prod_value_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4207 entries, 0 to 4206
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       4207 non-null   object
 1   Domain            4207 non-null   object
 2   Area Code (M49)   4207 non-null   int64
 3   Area              4207 non-null   object
 4   Element Code      4207 non-null   int64
 5   Element           4207 non-null   object
 6   Item Code (CPC)   4207 non-null   object
 7   Item              4207 non-null   object
 8   Year Code         4207 non-null   int64
 9   Year              4207 non-null   int64
 10  Unit              4207 non-null   object
 11  Value             4207 non-null   int64
 12  Flag              4207 non-null   object
 13  Flag Description  4207 non-null   object
dtypes: int64(5), object(9)
memory usage: 460.3+ KB

In [4]:
#View rows and column count
ag_prod_value_df.shape

(4207, 14)

In [5]:
# Check columns name if there is any irrelevant spelling
ag_prod_value_df.columns.values

array(['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code',
       'Element', 'Item Code (CPC)', 'Item', 'Year Code', 'Year', 'Unit',
       'Value', 'Flag', 'Flag Description'], dtype=object)

In [6]:
# Standardisation of column name -> Rename column name to keep a single uppercase to make easier our work with analysis. 
ag_prod_value_df.rename(columns = {"Domain Code" :"Domain_code", 
                                  "Domain": "Domain",
                                  "Area Code (M49)":"Area_code_m49",
                                  "Area":"Area",
                                  "Element Code":"Element_code",
                                  "Element": "Element",
                                  "Item Code (CPC)":"Item_code_cpc",
                                  "Item":"Item",
                                  "Year Code":"Year_code",
                                  "Year":"Year",
                                    "Unit": "Unit",
                                    "Value":"Value",
                                    "Flag":"Flag",
                                    "Flag Description" : "Flag_description"}, inplace = True)

In [7]:
# Let's view Unique Value in axes 0 -> In each Column
ag_prod_value_df.nunique(axis = 0)

Domain_code            1
Domain                 1
Area_code_m49          4
Area                   4
Element_code           5
Element                5
Item_code_cpc        132
Item                 132
Year_code              3
Year                   3
Unit                   3
Value               3438
Flag                   1
Flag_description       1
dtype: int64

In [8]:
#Removing column having a single value as these one wont help us to much for our analysis
#These columns are : Domain_code, Domain, Flag, Flag_description
#First lets see differenet values that they contain

print("##### Domain_code: #####")
print(pd.unique(ag_prod_value_df['Domain_code']))
print("\n##### Domain : #####")
print(pd.unique(ag_prod_value_df['Domain']))
print("\n##### Area_code_m49 : #####")
print(pd.unique(ag_prod_value_df['Area_code_m49']))

print("##### Area: #####")
print(pd.unique(ag_prod_value_df['Area']))
print("\n##### Flag : #####")
print(pd.unique(ag_prod_value_df['Flag']))
print("\n##### Flag_descritpion : #####")
print(pd.unique(ag_prod_value_df['Flag_description']))

##### Domain_code: #####
['QV']

##### Domain : #####
['Value of Agricultural Production']

##### Area_code_m49 : #####
[250 372 724 840]
##### Area: #####
['France' 'Ireland' 'Spain' 'United States of America']

##### Flag : #####
['E']

##### Flag_descritpion : #####
['Estimated value']

In [9]:
#Removal of columns
ag_prod_value_df = ag_prod_value_df.drop(['Domain_code','Domain','Flag','Flag_description'], axis=1)

#View after Removal
ag_prod_value_df.head()

,Area_code_m49,Area,Element_code,Element,Item_code_cpc,Item,Year_code,Year,Unit,Value
0,250,France,152,Gross Production Value (constant 2014-2016 tho...,01371,"Almonds, in shell",2018,2018,1000 Int. $,5713
1,250,France,152,Gross Production Value (constant 2014-2016 tho...,01371,"Almonds, in shell",2019,2019,1000 Int. $,5713
2,250,France,152,Gross Production Value (constant 2014-2016 tho...,01371,"Almonds, in shell",2020,2020,1000 Int. $,5916
3,250,France,152,Gross Production Value (constant 2014-2016 tho...,01341,Apples,2018,2018,1000 Int. $,821448
4,250,France,152,Gross Production Value (constant 2014-2016 tho...,01341,Apples,2019,2019,1000 Int. $,827655

In [10]:
#Check also the value in Element and Element_code
print("\n##### Element : #####")
print(pd.unique(ag_prod_value_df['Element']))
print("\n##### Element_code : #####")
print(pd.unique(ag_prod_value_df['Element_code']))
print("\n##### Unit : #####")
print(pd.unique(ag_prod_value_df['Unit']))


# Definitions and standards used in FAOSTAT 
# I$ = international dollar
# SLC = standard local currency

##### Element : #####
['Gross Production Value (constant 2014-2016 thousand I$)'
 'Gross Production Value (current thousand SLC)'
 'Gross Production Value (constant 2014-2016 thousand SLC)'
 'Gross Production Value (current thousand US$)'
 'Gross Production Value (constant 2014-2016 thousand US$)']

##### Element_code : #####
[152  56  55  57  58]

##### Unit : #####
['1000 Int. $' '1000 SLC' '1000 US$']

In [11]:
## For simplification purpose we consider that the Unit is the US dollar, and SLC for Ireland/France/Spain is 1 Euro = 1 Dollar.
## Lets Remove unnecessary Column: Element, Element_code, Year_code
ag_prod_value_df = ag_prod_value_df.drop(['Element','Element_code','Year_code'], axis=1)
ag_prod_value_df.head()

,Area_code_m49,Area,Item_code_cpc,Item,Year,Unit,Value
0,250,France,01371,"Almonds, in shell",2018,1000 Int. $,5713
1,250,France,01371,"Almonds, in shell",2019,1000 Int. $,5713
2,250,France,01371,"Almonds, in shell",2020,1000 Int. $,5916
3,250,France,01341,Apples,2018,1000 Int. $,821448
4,250,France,01341,Apples,2019,1000 Int. $,827655

In [12]:
## Check values in Item
print("\n##### Item : #####")
print(pd.unique(ag_prod_value_df['Item']))

##### Item : #####
['Almonds, in shell' 'Apples' 'Apricots' 'Artichokes' 'Asparagus'
 'Avocados' 'Bananas' 'Barley' 'Blueberries'
 'Broad beans and horse beans, dry' 'Broad beans and horse beans, green'
 'Cabbages' 'Cantaloupes and other melons' 'Carrots and turnips'
 'Cauliflowers and broccoli' 'Cereals n.e.c.' 'Cherries'
 'Chestnuts, in shell'
 'Chillies and peppers, green (Capsicum spp. and Pimenta spp.)'
 'Cucumbers and gherkins' 'Currants' 'Eggplants (aubergines)' 'Figs'
 'Flax, processed but not spun' 'Grapes' 'Green garlic'
 'Hazelnuts, in shell' 'Hen eggs in shell, fresh' 'Hop cones'
 'Horse meat, fresh or chilled'
 'Horse meat, fresh or chilled (indigenous)' 'Kiwi fruit'
 'Leeks and other alliaceous vegetables' 'Lemons and limes'
 'Lettuce and chicory' 'Linseed' 'Lupins' 'Maize (corn)'
 'Meat of cattle with the bone, fresh or chilled'
 'Meat of cattle with the bone, fresh or chilled (indigenous)'
 'Meat of chickens, fresh or chilled'
 'Meat of chickens, fresh or chilled (indigenous)'
 'Meat of ducks, fresh or chilled'
 'Meat of ducks, fresh or chilled (indigenous)'
 'Meat of geese, fresh or chilled'
 'Meat of geese, fresh or chilled (indigenous)'
 'Meat of goat, fresh or chilled'
 'Meat of goat, fresh or chilled (indigenous)'
 'Meat of pig with the bone, fresh or chilled'
 'Meat of pig with the bone, fresh or chilled (indigenous)'
 'Meat of rabbits and hares, fresh or chilled'
 'Meat of rabbits and hares, fresh or chilled (indigenous)'
 'Meat of sheep, fresh or chilled'
 'Meat of sheep, fresh or chilled (indigenous)'
 'Meat of turkeys, fresh or chilled'
 'Meat of turkeys, fresh or chilled (indigenous)' 'Mixed grain'
 'Mushrooms and truffles' 'Natural honey' 'Oats' 'Olives'
 'Onions and shallots, dry (excluding dehydrated)' 'Oranges'
 'Other beans, green'
 'Other nuts (excluding wild edible nuts and groundnuts), in shell, n.e.c.'
 'Other oil seeds, n.e.c.' 'Other pulses n.e.c.' 'Other stone fruits'
 'Other tropical fruits, n.e.c.' 'Other vegetables, fresh n.e.c.'
 'Peaches and nectarines' 'Pears' 'Peas, dry' 'Peas, green'
 'Plums and sloes' 'Pomelos and grapefruits' 'Potatoes'
 'Pumpkins, squash and gourds' 'Rape or colza seed' 'Raspberries'
 'Raw milk of cattle' 'Raw milk of goats' 'Raw milk of sheep' 'Rice' 'Rye'
 'Shorn wool, greasy, including fleece-washed shorn wool' 'Sorghum'
 'Sour cherries' 'Soya beans' 'Spinach' 'Strawberries' 'Sugar beet'
 'Sunflower seed' 'Tangerines, mandarins, clementines' 'Tomatoes'
 'Triticale' 'True hemp, raw or retted' 'Unmanufactured tobacco'
 'Walnuts, in shell' 'Watermelons' 'Wheat'
 'Other berries and fruits of the genus vaccinium n.e.c.'
 'Other citrus fruit, n.e.c.' 'Other pome fruits' 'Peppermint, spearmint'
 'Seed cotton, unginned' 'Beans, dry' 'Beeswax' 'Buckwheat'
 'Chick peas, dry' 'Coffee, green' 'Cow peas, dry' 'Cranberries' 'Dates'
 'Game meat, fresh, chilled or frozen' 'Ginger, raw' 'Green corn (maize)'
 'Groundnuts, excluding shelled' 'Lentils, dry'
 'Mangoes, guavas and mangosteens' 'Millet' 'Mustard seed' 'Okra'
 'Other fruits, n.e.c.' 'Papayas' 'Pineapples' 'Pistachios, in shell'
 'Safflower seed' 'String beans' 'Sugar cane' 'Sweet potatoes' 'Taro']

In [13]:
## We will focus on Meat and Milk Production value 
## lets simplify our dataframe creating a new one containing only meat and milk data

In [14]:
meat_milk_df = ag_prod_value_df.loc[(ag_prod_value_df['Item'].str.contains('Meat'))|(ag_prod_value_df['Item'].str.contains('meat'))|(ag_prod_value_df['Item'].str.contains('milk'))]

In [15]:
#Quick Overview of the dataframe
meat_milk_df.head()

,Area_code_m49,Area,Item_code_cpc,Item,Year,Unit,Value
279,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,17237
280,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,17947
281,250,France,21118.01,"Horse meat, fresh or chilled",2020,1000 SLC,18806
282,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,13054
283,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,13054

In [16]:
meat_milk_df.shape

(806, 7)

In [17]:
#Let's check that we have all values in which we are focusing
## Check values in Item
print("\n##### Item : #####")
print(pd.unique(meat_milk_df['Item']))

##### Item : #####
['Horse meat, fresh or chilled'
 'Horse meat, fresh or chilled (indigenous)'
 'Meat of cattle with the bone, fresh or chilled'
 'Meat of cattle with the bone, fresh or chilled (indigenous)'
 'Meat of chickens, fresh or chilled'
 'Meat of chickens, fresh or chilled (indigenous)'
 'Meat of ducks, fresh or chilled'
 'Meat of ducks, fresh or chilled (indigenous)'
 'Meat of geese, fresh or chilled'
 'Meat of geese, fresh or chilled (indigenous)'
 'Meat of goat, fresh or chilled'
 'Meat of goat, fresh or chilled (indigenous)'
 'Meat of pig with the bone, fresh or chilled'
 'Meat of pig with the bone, fresh or chilled (indigenous)'
 'Meat of rabbits and hares, fresh or chilled'
 'Meat of rabbits and hares, fresh or chilled (indigenous)'
 'Meat of sheep, fresh or chilled'
 'Meat of sheep, fresh or chilled (indigenous)'
 'Meat of turkeys, fresh or chilled'
 'Meat of turkeys, fresh or chilled (indigenous)' 'Raw milk of cattle'
 'Raw milk of goats' 'Raw milk of sheep'
 'Game meat, fresh, chilled or frozen']

In [18]:
# More Interesting to categories and classify these creating 3 new columns
# Category Column -> To Classify by type MEAT or MILK
# Animal Column -> To have clear overview of which Animal Type(Sheep, Chicken etc....) 
# Animal_group will -> contains following values
# CATTLE(cattle only), POULTRY(chickens, ducks, geese, rabbits, turkey), SHEEP(sheep,pig), OTHER(Horse, Game)

In [19]:
#Create Category Column
meat_milk_df['Category'] = np.where(meat_milk_df['Item'].str.contains('milk'),'MILK','MEAT')

In [20]:
#Quick Overview
meat_milk_df.head()

,Area_code_m49,Area,Item_code_cpc,Item,Year,Unit,Value,Category
279,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,17237,MEAT
280,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,17947,MEAT
281,250,France,21118.01,"Horse meat, fresh or chilled",2020,1000 SLC,18806,MEAT
282,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,13054,MEAT
283,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,13054,MEAT

In [21]:
#Creating Animal Column
conditions = [meat_milk_df['Item'].str.contains('Horse'), 
              meat_milk_df['Item'].str.contains('cattle'),
             meat_milk_df['Item'].str.contains('chickens'),
              meat_milk_df['Item'].str.contains('ducks'),  
              meat_milk_df['Item'].str.contains('geese'),
              meat_milk_df['Item'].str.contains('goat'),
             meat_milk_df['Item'].str.contains('pig'),
              meat_milk_df['Item'].str.contains('rabbits'), 
             meat_milk_df['Item'].str.contains('sheep'),
             meat_milk_df['Item'].str.contains('turkeys'),
              meat_milk_df['Item'].str.contains('goats'),
              meat_milk_df['Item'].str.contains('Game')]

choices = ['Horse','Cattle','Chicken','Duck', 'Geese','Goat','Pig','Rabbit', 'Sheep', 'Turkey','Goat','Game']
meat_milk_df['Animal'] = np.select(conditions,choices,default="")

In [22]:
meat_milk_df.head()

,Area_code_m49,Area,Item_code_cpc,Item,Year,Unit,Value,Category,Animal
279,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,17237,MEAT,Horse
280,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,17947,MEAT,Horse
281,250,France,21118.01,"Horse meat, fresh or chilled",2020,1000 SLC,18806,MEAT,Horse
282,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,13054,MEAT,Horse
283,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,13054,MEAT,Horse

In [23]:
#Remind quickly available values
pd.unique(meat_milk_df['Animal'])

array(['Horse', 'Cattle', 'Chicken', 'Duck', 'Geese', 'Goat', 'Pig',
       'Rabbit', 'Sheep', 'Turkey', 'Game'], dtype=object)

In [24]:
# Creating the Animal_group column to classify the production of meat.
# CATTLE(cattle only), POULTRY(chickens, ducks, geese, rabbits, turkey), SHEEP(sheep), OTHER(Horse, Game, Pig)

animal_group_dictionnary = {'Horse':'Other', 'Cattle':'Cattle', 'Chicken':'Poultry', 
                            'Duck':'Poultry', 'Geese':'Poultry', 'Goat':'Sheep', 'Pig':'Other',
                            'Rabbit':'Poultry', 'Sheep':'Sheep', 'Turkey':'Poultry', 'Game':'Other' }

meat_milk_df['Animal_group'] = meat_milk_df['Animal'].map(animal_group_dictionnary)

In [25]:
#Quick check of new DF
meat_milk_df.head()

,Area_code_m49,Area,Item_code_cpc,Item,Year,Unit,Value,Category,Animal,Animal_group
279,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,17237,MEAT,Horse,Other
280,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,17947,MEAT,Horse,Other
281,250,France,21118.01,"Horse meat, fresh or chilled",2020,1000 SLC,18806,MEAT,Horse,Other
282,250,France,21118.01,"Horse meat, fresh or chilled",2018,1000 SLC,13054,MEAT,Horse,Other
283,250,France,21118.01,"Horse meat, fresh or chilled",2019,1000 SLC,13054,MEAT,Horse,Other

In [26]:
#Review of result 
pd.unique(meat_milk_df['Animal_group'])

array(['Other', 'Cattle', 'Poultry', 'Sheep'], dtype=object)

In [27]:
#Check if we need to remove rows with nan values 
print(meat_milk_df.isnull().sum())

Area_code_m49    0
Area             0
Item_code_cpc    0
Item             0
Year             0
Unit             0
Value            0
Category         0
Animal           0
Animal_group     0
dtype: int64

In [28]:
#Last Check to view if we are ready to plot all these and start our analysis
meat_milk_df.count()

Area_code_m49    806
Area             806
Item_code_cpc    806
Item             806
Year             806
Unit             806
Value            806
Category         806
Animal           806
Animal_group     806
dtype: int64

In [29]:
#Check the shape of the DF
meat_milk_df.shape

(806, 10)

### Our Conclusion : 
Our Dataframe doenst contain any null value, and is ready to be plotted and we can start our work around.

## Visualization of our dataframe for Ireland only

In [30]:
# Import interactive Altair library
import altair as alt

# First Overview of the Interactive View for Ireland
ir_prod = meat_milk_df.loc[meat_milk_df['Area']=='Ireland']
alt.Chart(ir_prod).mark_point().encode(
    alt.X('Animal'),
    alt.Y('Value')
).properties(
    width=800,
    height=300
).configure_point(
    size=100)

alt.Chart(...)

In [31]:
select_country = alt.selection_single(
    name='select', fields=['Year'], init={'Year': '2018'},
    bind=alt.binding_range(min=2018, max=2020, step=1)
)
alt.Chart(ir_prod).mark_point(filled=True).encode(
    alt.X('Animal', scale=alt.Scale(zero=False)),
    alt.Y('Value', scale=alt.Scale(zero=False)),
    
).add_selection(select_country).transform_filter(select_country).properties(
    width=800,
    height=300
).configure_point(
    size=100)

alt.Chart(...)

## Our Conclusion :
We can remark that cattle production value is the highest type, followed by pig and sheep in the last 3 years.

## 2 - STATISTICS ON THE CAP PERFORMANCE ON MEAT MILK PRODUCTION VALUE

For simplification purpose we will study the performance on the last 3 years available in our dataframe those are 2020,2019,2018. We will compare our performance with other top 2 countries of EU in the agriculture production (France, Spain). We will use data provided by the agridata website. The CAP provide income support for farmers in each EU member country. The Income Support Amount is calculated as follow : 
Number of CAP beneficiary (for the Year) multiply Amount per CAP beneficary (for the Year).

I see that in the public website we dont have appropriate dataset, all dataset are bulked with too much unnecessary data for our analysis. I build the dataframe manually as it will save time and coding lines.

The source of these numbers are from the visual dashboard of agridata.

In [41]:
# Lets built the cap_df dataframe first according to the value provided by agridata website.
# Data is as follow :
# 2018, EU, 6158770, 6480 - France, 325810, 22990 - Ireland, 123300, 10330 - Spain, 663190, 7460
# 2019, EU, 6064820, 6610 - France, 321110, 23370 - Ireland, 122580, 10540 - Spain, 654400, 7620
# 2020, EU, 5996360, 6620 - France, 316120, 23400 - Ireland, 122450, 10540 - spain, 644500, 7590


cap_df = pd.DataFrame(
    
    {
    'Year' : [2018,2018,2018,2018,2019,2019,2019,2019,2020,2020,2020,2020], 
    'Entity':['EU', 'France', 'Ireland', 'Spain','EU', 'France', 'Ireland', 'Spain', 'EU', 'France', 'Ireland', 'Spain'],
    'Beneficiary_number' : [6158770,325810,123300,663190,6064820,321110,122580,654400,5996360,316120,122450,644500],
    'Amount_per_beneficiary' : [6480,22990,10330,7460,6610,23370,10540,7620,6620,23400,10540,7590],
    }

)

In [42]:
#Quick Overview
cap_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    12 non-null     int64
 1   Entity                  12 non-null     object
 2   Beneficiary_number      12 non-null     int64
 3   Amount_per_beneficiary  12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 512.0+ bytes

In [43]:
#Quick Overview
cap_df.head()

   Year   Entity  Beneficiary_number  Amount_per_beneficiary
0  2018       EU             6158770                    6480
1  2018   France              325810                   22990
2  2018  Ireland              123300                   10330
3  2018    Spain              663190                    7460
4  2019       EU             6064820                    6610

In [44]:
cap_df['Total_amount'] = cap_df['Amount_per_beneficiary']*cap_df['Beneficiary_number']

In [39]:
cap_df.head()

   Year   Entity  Beneficiary_number  Amount_per_beneficiary  Total_amount
0  2018       EU             6158770                    6480   39908829600
1  2018   France              325810                   22990    7490371900
2  2018  Ireland              123300                   10330    1273689000
3  2018    Spain              663190                    7460    4947397400
4  2019       EU             6064820                    6610   40088460200

In [ ]:
#Quick Overview of different value contained in each column 
# Visualize different value we have for some attributes to understand how we can progress in our anlysis.


print("\n##### Movement values Are : #####")
print(pd.unique(df['Movement']))
print("\n##### Date values Are : #####")
print(pd.unique(df['Date']))
print("\n##### Time values Are : #####")
print(pd.unique(df['Time']))
print("\n##### Count_type values Are : #####")
print(pd.unique(df['Count_type']))
print("\n##### Arm_crossed values Are : #####")
print(pd.unique(df['Arm_crossed']))
print("\n##### Arm_location values Are : #####")
print(pd.unique(df['Arm_location']))

In [ ]:
#Plot production of Agriculture for the last 5 Years. 
#Display data per year.
plt.rcParams["figure.dpi"] = 164 #Customizing sizing of display
ir_prod_count = ir_prod_value_df.groupby("Item_code_cpc").sum()
ir_prod_count.plot(kind="bar", title="PRODUCTION", color ="r", xlabel="ITEM_CPC_CODE", ylabel="VALUE")